// DPlayer/vue-sample/src/components/Player.vue
<template>
  <div id="video" ref="videoRef" style="width: 100%; maxWidth: 800px"/>
</template>

<script>
import DPlayer from 'dplayer';
import Hls from 'hls.js';
import mux from 'mux-embed';

import { HLSLoader } from '@mlytics/p2sp-sdk/driver/integration/streaming/hls';

export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Player',
  props: {
    options: {
      type: Object
    }
  },
  data() {
    return {
      dp: null
    };
  },
  async mounted() {
    const { source, autoplay, controls } = this.options;
    const { src } = source;
    const video = this.$refs.videoRef;

    let type = 'normal';
    if (Hls.isSupported()) {
      type = 'customHls';
    } else {
      alert("hls is not supported.")
    }

    this.dp = new DPlayer({
      container: video,
      autoplay,
      controls,
      video: {
        url: src,
        type,
        customType: {
          customHls: (video) => {
            const hls = new Hls({
              loader: HLSLoader
            });
            hls.loadSource(video.src);
            hls.attachMedia(video);

            const muxOptions = {
              ...this.options.mux,
              hlsjs: hls,
              Hls: Hls
            }
            mux.monitor(video, muxOptions);
          }
        }
      }
    });
  },
  async beforeUnmount() {
    if (this.dp) this.dp.destroy();
  }
};
</script>

// DPlayer/react-sample/src/components/Player.js
import { useEffect, useRef } from 'react';

import DPlayer from 'dplayer';
import Hls from 'hls.js';
import mux from 'mux-embed';

import { HLSLoader } from '@mlytics/p2sp-sdk/driver/integration/streaming/hls';

const Player = (props) => {
  const videoRef = useRef(null);
  const dpRef = useRef(null);

  useEffect(() => {
    const { source, autoplay, controls } = props.options;
    const { src } = source;

    const video = videoRef.current;
    dpRef.current = new DPlayer({
      container: video,
      autoplay,
      controls,
      video: {
        url: src,
        type: 'customHls',
        customType: {
          customHls: (video) => {
            const hls = new Hls({
              loader: HLSLoader
            });
            hls.loadSource(video.src);
            hls.attachMedia(video);

            const muxOptions = {
              ...props.options.mux,
              hlsjs: hls,
              Hls: Hls
            }
            mux.monitor(video, muxOptions);
          }
        }
      }
    });

  }, [videoRef]);

  useEffect(() => {
    const dp = dpRef.current;
    return () => {
      if (dp) dp.destroy();
    }
  }, [dpRef]);

  return (
    <div id="video" ref={videoRef} style={{width: "100%", maxWidth: "800px"}}/>
  );
}
export default Player;
