// HLS.js/react-sample/src/components/Player.js
import { useEffect, useRef } from 'react';

import Hls from 'hls.js';
import mux from 'mux-embed';

import { HLSLoader } from '@mlytics/p2sp-sdk/driver/integration/streaming/hls';

const Player = (props) => {
  const videoRef = useRef(null);
  const hlsRef = useRef(null);

  useEffect(() => {
    const hls = hlsRef.current;
    return () => {
      if (hls) {
        hls.destroyed();
      }
    }
  }, []);

  useEffect(() => {
    const { source } = props.options;
    const { src } = source;

    const video = videoRef.current;
    let hls = hlsRef.current;
    if (Hls.isSupported() && !hls) {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      hlsRef.current = new Hls({
        loader: HLSLoader
      });
      hls = hlsRef.current;
      hls.loadSource(src);
      hls.attachMedia(video);
      if (props.options.mux) {
        const muxOptions = {
          ...props.options.mux,
          hlsjs: hls,
          Hls: Hls,
        }
        mux.monitor(video, muxOptions);
      }
    }

  }, [videoRef]);

  const { controls, autoplay } = props.options;
  return (
    <video
      controls={controls}
      autoPlay={autoplay}
      ref={videoRef}
      style={{ width: "100%", maxWidth: "800px" }} />
  );
}
export default Player;

// DPlayer/vue-sample/src/components/Player.vue
<template>
  <div id="video" ref="videoRef" style="width: 100%; maxWidth: 800px"/>
</template>

<script>
import DPlayer from 'dplayer';
import Hls from 'hls.js';
import mux from 'mux-embed';

import { HLSLoader } from '@mlytics/p2sp-sdk/driver/integration/streaming/hls';

export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Player',
  props: {
    options: {
      type: Object
    }
  },
  data() {
    return {
      dp: null
    };
  },
  async mounted() {
    const { source, autoplay, controls } = this.options;
    const { src } = source;
    const video = this.$refs.videoRef;

    let type = 'normal';
    if (Hls.isSupported()) {
      type = 'customHls';
    } else {
      alert("hls is not supported.")
    }

    this.dp = new DPlayer({
      container: video,
      autoplay,
      controls,
      video: {
        url: src,
        type,
        customType: {
          customHls: (video) => {
            const hls = new Hls({
              loader: HLSLoader
            });
            hls.loadSource(video.src);
            hls.attachMedia(video);

            const muxOptions = {
              ...this.options.mux,
              hlsjs: hls,
              Hls: Hls
            }
            mux.monitor(video, muxOptions);
          }
        }
      }
    });
  },
  async beforeUnmount() {
    if (this.dp) this.dp.destroy();
  }
};
</script>
