// HLS.js/react-sample/src/components/Player.js
import { useEffect, useRef } from 'react';

import Hls from 'hls.js';
import mux from 'mux-embed';

import { HLSLoader } from '@mlytics/p2sp-sdk/driver/integration/streaming/hls';

const Player = (props) => {
  const videoRef = useRef(null);
  const hlsRef = useRef(null);

  useEffect(() => {
    const hls = hlsRef.current;
    return () => {
      if (hls) {
        hls.destroyed();
      }
    }
  }, []);

  useEffect(() => {
    const { source } = props.options;
    const { src } = source;

    const video = videoRef.current;
    let hls = hlsRef.current;
    if (Hls.isSupported() && !hls) {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      hlsRef.current = new Hls({
        loader: HLSLoader
      });
      hls = hlsRef.current;
      hls.loadSource(src);
      hls.attachMedia(video);
      if (props.options.mux) {
        const muxOptions = {
          ...props.options.mux,
          hlsjs: hls,
          Hls: Hls,
        }
        mux.monitor(video, muxOptions);
      }
    }

  }, [videoRef]);

  const { controls, autoplay } = props.options;
  return (
    <video
      controls={controls}
      autoPlay={autoplay}
      ref={videoRef}
      style={{ width: "100%", maxWidth: "800px" }} />
  );
}
export default Player;

// HLS.js/vue-sample/src/components/Player.vue
<template>
  <video id="video" ref="videoRef" style="width: 100%; maxWidth: 800px" :controls="options.controls"
    :autoplay="options.autoplay" />
</template>

<script>
import Hls from 'hls.js'
import mux from 'mux-embed';

export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Player',
  props: {
    options: {
      type: Object
    }
  },
  data() {
    return {
      hls: null
    };
  },
  async mounted() {
    const { hlsConfig, source } = this.options;
    const { src } = source;

    const video = this.$refs.videoRef;
    if (video) {
      if (Hls.isSupported() && !this.hls) {
        this.hls = new Hls({
          loader: hlsConfig.loader
        });
        this.hls.loadSource(src);
        this.hls.attachMedia(video);

        const muxOptions = {
          ...this.options.mux,
          hlsjs: this.hls,
          Hls: Hls,
        }
        mux.monitor(video, muxOptions);
      }
    }
  },
  async beforeUnmount() {
    if (this.hls) {
      this.hls.destroy();
    }
  }
};
</script>
